# Use postgres/example user/password credentials
version: '3.5'

services:
  keycloak:
    image: jboss/keycloak
    restart: always
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_ADDR: postgres
      DB_USER: keycloak
      DB_PASSWORD: keycloak
    ports:
      - 8080:8080