# Use postgres/example user/password credentials
version: '3.5'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
       - //d/kdi/docker/volumes/postgres/12/data:/data/postgres   
    ports:
      - 5432:5432
    restart: unless-stopped
      
  pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-rafaelsalles.sistemas@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-postgres}
    ports:
      - 5050:80
    restart: unless-stopped 
    depends_on:
      - postgres