version: "3.8"
services:
  sonar-db:
    image: 'bitnami/postgresql:latest'
    container_name: postgres-bitnami
    environment:
      POSTGRESQL_USERNAME: bn_sonarqube
      POSTGRESQL_DATABASE: bitnami_sonarqube
      POSTGRESQL_PASSWORD: bitnami1234
    ports:
      - 5433:5432
  sonar:
    image: 'bitnami/sonarqube:latest'
    ports:
      - '9000:9000'
    environment:
      POSTGRESQL_HOST: sonar-db
      SONARQUBE_DATABASE_USER: bn_sonarqube
      SONARQUBE_DATABASE_NAME: bitnami_sonarqube
      SONARQUBE_DATABASE_PASSWORD: bitnami1234
    depends_on:
      - "sonar-db"

volumes:
  shared:
  sonarqube_data:

