version: "3.8"
services:
  keycloak-db:
    image: 'bitnami/postgresql:latest'
    container_name: postgres-bitnami
    environment:
      POSTGRESQL_USERNAME: keycloak
      POSTGRESQL_DATABASE: keycloak
      POSTGRESQL_PASSWORD: keycloak
    ports:
      - 5434:5432
  keycloak:
    image: 'bitnami/keycloak:latest'
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_MANAGEMENT_USER: manager
      KEYCLOAK_MANAGEMENT_PASSWORD: manager
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_HOST: host.docker.internal
      KEYCLOAK_DATABASE_PORT: 5434
      KEYCLOAK_DATABASE_USER: keycloak
      KEYCLOAK_DATABASE_PASSWORD: keycloak
    ports:
      - "80:8080"
    depends_on:
      - "keycloak-db"

  pingfederate:
    container_name: pingfederate
    image: 'pingidentity/pingfederate:latest'
    command: wait-for pingdirectory:1389 -t 900 -- entrypoint.sh start-server
    environment:
      SERVER_PROFILE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
      SERVER_PROFILE_PATH: baseline/pingfederate
    ports:
      - "9031:9031"
      - "9999:9999"

  localstack:
    container_name: awslocal
    image: itau-el4-cloud-docker.appdes.artifactory.prod.cloud.ihf/localstack
    hostname: awslocal
    ports:
      - 4566:4566
    environment:
      #SERVICES: dynamodb,s3
      SERVICES: secretsmanager
      DEBUG: 1
      DATA_DIR: /tmp/localstack/data
      HOST_TMP_FOLDER: /tmp/localstack
      HOSTNAME_EXTERNAL: awslocal
    volumes:
      - ./assets:/opt/code/localstack/test

volumes:
  shared:
  sonarqube_data:
  postgresql_data:

  #docker-compose up -d --build --force-recreate jaeger db app app-gateway swagger

  #docker-compose up -d --build --force-recreate jaeger app app-gateway

  #winpty docker exec -ti awslocal bash
  #aws configure
  #login e senha padrão escolher
  #region: sa-east-1

  #docker run -it -v C:\Users\RABARSL\git\ua2\justcodeplatform-uadcredlinelogonapi\app\src\main\proto:/proto -v C:\Users\rabarsl\gateway:/output -e GRPC_SERVER_ENDPOINT=localhost:50051 -e BUILDOS=windows itau-ey5-docker.depdes.artifactory.prod.cloud.ihf/orangestack-grpcgateway:latest
