version: "3.8"
services:
  keycloak-db:
    image: 'bitnami/postgresql:latest'
    container_name: postgres-bitnami
    environment:
      POSTGRESQL_USERNAME: keycloak
      POSTGRESQL_DATABASE: keycloak
      POSTGRESQL_PASSWORD: keycloak
    ports:
      - 5434:5432
  keycloak:
    image: 'bitnami/keycloak:latest'
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_MANAGEMENT_USER: manager
      KEYCLOAK_MANAGEMENT_PASSWORD: manager
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_HOST: host.docker.internal
      KEYCLOAK_DATABASE_PORT: 5434
      KEYCLOAK_DATABASE_USER: keycloak
      KEYCLOAK_DATABASE_PASSWORD: keycloak
    ports:
      - "80:8080"
    depends_on:
      - "keycloak-db"

volumes:
  shared:
  postgresql_data:
